name: security
"on":
  push:
    branches:
      - main
jobs:
  scan_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          pip install detect-secrets
      - name: Scan for secrets
        run: |
          detect-secrets scan --all-files
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
        with:
          args: '--sarif-file-output=snyk.sarif'
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
      - name: Set Up Java
        uses: actions/setup-java@v2
        with:
         java-version: '11'

      - name: Install Veracode CLI
        run: |
         curl -o veracode.zip https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
          unzip veracode.zip
          mv pipeline-scan* veracode
          export PATH=$PATH:$PWD/veracode
        shell: bash

      - name: Configure Veracode
        run: |
         veracode --version
         veracode auth init -t <VERACODE_API_ID> -k <VERACODE_API_KEY>
        env:
         VERACODE_API_ID: ${{ secrets.VERACODE_API_ID }}
         VERACODE_API_KEY: ${{ secrets.VERACODE_API_KEY }}

      - name: Static Scan
        run: |
         veracode --version
         veracode scan -f <VERACODE_APP_NAME> -b <VERACODE_BUILD_NAME> -d <PATH_TO_SOURCE_CODE>
        env:
         VERACODE_APP_NAME: 'YourAppName'
         VERACODE_BUILD_NAME: 'YourBuildName'
        working-directory: /github/workspace

      - name: Upload Results
        run: |
         veracode uploadresults -b <VERACODE_BUILD_NAME> -f json
        env:
         VERACODE_BUILD_NAME: 'YourBuildName'
        working-directory: /github/workspace

      - name: Veracode Scan Report
        run: |
         veracode results -b <VERACODE_BUILD_NAME> -f json
        env:
         VERACODE_BUILD_NAME: 'YourBuildName'
        working-directory: /github/workspace    
